groups/urls.py
from django.urls import path
from . import views

app_name= 'groups'

urlpatterns =[
    path('', views.ListGroup.as_view(), name='all'),
    path('new/', views.CreateGroup.as_view(), name='create'),
    path('post/in/<str:slug>/', views.SingleGroup.as_view(), name='single'),
    path('join/<str:slug>/', views.JoinGroup.as_view(), name='join'),
    path('leave/<str:slug>/', views.LeaveGroup.as_view(), name='leave'),
]

posts/urls.py
from django.urls import path
from . import views

app_name='posts'

urlpatterns = [
    path('', views.PostList.as_view(), name='all'),
    path('new/', views.CreatePost.as_view(), name='create'),
    path('by/<str:username>/', views.UserPosts.as_view(), name='for_user'),
    path('by/<str:username>/<int:pk>/', views.PostDetail.as_view(), name='single'),
    path('delete/<int:pk>/', views.DeletePost.as_view(), name='delete'),

    #personalpost model
    path('personalpost/', views.PorsonalPostList.as_view(), name='personalpost'),
    path('personalpost/new/', views.PersonalPostCreate.as_view(), name='createpost'),
    path('personalpost/detail/<int:pk>/', views.PersonalPostDetail.as_view(), name='post_detail'),
    path('personalpost/remove/<int:pk>/', views.PersonalPostDelete.as_view(), name='deletepost'),
]

simplesocial/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.HomePage.as_view(), name='home'),
    path('accounts/',include('accounts.urls', namespace='accounts')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('test/', views.TestPage.as_view(), name='test'),
    path('thanks/', views.ThanksPage.as_view(), name='thanks'),
    path('groups/',include('groups.urls', namespace='groups')),
    path('posts/', include('posts.urls', namespace='posts')),
    path('comments/', include('comments.urls', namespace='comments')),


]

groups/models.py
from django.db import models
from django.urls import reverse
from django.utils.text import slugify
import misaka

from django.contrib.auth import get_user_model
User = get_user_model()

from django import template
register = template.Library()

# Create your models here.

class Group(models.Model):
    name = models.CharField(max_length=255, unique=True)
    slug = models.SlugField(allow_unicode=True, unique=True)
    description = models.TextField(blank=True, default="")
    description_html = models.TextField(editable=False, default="", blank=True)
    members = models.ManyToManyField(User, through='GroupMember')

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        self.description_html = misaka.html(self.description)
        super().save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse('groups:single', kwargs={'slug':self.slug})

    def __str__(self):
        return self.name

    class Meta():
        ordering = ['name']


class GroupMember(models.Model):
    group = models.ForeignKey('groups.Group', related_name='memberships', on_delete= models.CASCADE)
    user = models.ForeignKey(User, related_name='user_group', on_delete= models.CASCADE)

    def __str__(self):
        return self.user.username

    class Meta():
        unique_together = ('group', 'user')

groups/views.py
import imp
from django.contrib import messages
from django.db import IntegrityError
from django.shortcuts import get_object_or_404, render
from django.urls import reverse
from django.views import generic
from django.contrib.auth.mixins import (LoginRequiredMixin, PermissionRequiredMixin)
from . import models
# Create your views here.
class CreateGroup(LoginRequiredMixin, generic.CreateView):
    model = models.Group
    fields = ['name', 'description']


class SingleGroup(generic.DetailView):
    model = models.Group
    


class ListGroup(generic.ListView):
    model = models.Group

class JoinGroup(LoginRequiredMixin, generic.RedirectView):

    def get_redirect_url(self,*args, **kwargs):
        return reverse('groups:single', kwargs={'slug':self.kwargs.get('slug')})

    '''make checks if user in group or not '''
    def get(self, request, *args, **kwargs):
        #Try to get the exactly group or give 404 page
        group = get_object_or_404(models.Group, slug=self.kwargs.get('slug'))

        try:
            models.GroupMember.objects.create(user=self.request.user, group=group)

        except IntegrityError:
            messages.warning(self.request,'Warning already a member!')

        else:
            messages.success(self.request,'You are now a member!')

        return super().get(request,*args,**kwargs)


class LeaveGroup(LoginRequiredMixin, generic.RedirectView):

    def get_redirect_url(self, *args, **kwargs):
        return reverse('groups:single', kwargs={'slug':self.kwargs.get('slug')})

    def get(self, request, *args, **kwargs):
        try:
            membership = models.GroupMember.get.objects.filter(user=self.request.user, group__slug=self.kwargs.get('slug')).get()

        except models.GroupMember.DoesNotExist:
            messages.warning(self.request,'Sorry you are not in this group !')

        else:
            membership.delete()
            messages.success(self.request,'You have left the group !')

        return super().get(request,*args,**kwargs)

groups/templates/groups/group_base.html
{% extends 'base.html' %}
<title>{% block title %} mood {% endblock%}</title> 

{% block body_blcok %}

<div class="container">
    <div class="row">
        {% block pregroup %} {% endblock %}
        {% block group_content %} {% endblock %}
        {% block postgroup %} {% endblock %}
    </div>
</div>
{% endblock %}

groups/templates/groups/group_detail.html
{% extends 'groups/group_base.html' %}

{% block pregroup %} 
    <h1>{{group.name}}</h1>
    <h3>Members Count:{{group.members.count}}</h3>

    {% if user in group.members.all %}
        <a href="{% url 'groups:leave' slug=group.slug %}" class="btn btn-lg btn-fill btn-waring"><i class="bi bi-box-arrow-left"></i>Leave</a>

        {% else %}
        <a href="{% url 'groups:join' slug=group.slug %}" class="btn btn-lg btn-fill btn-waring"><i class="bi bi-box-arrow-in-right"></i>Join</a>
    {% endif %}

{% endblock %}

{% block group_content %}
    <div class="col-md-8">
        {% if group.posts.count == 0 %}
                <h2>No Post</h2>
            
            {% else %}

            {% for post in group.posts.all %}
                {{post}}
                {% include "posts/_post.html" %}
            {% endfor %}
        {% endif %}

    </div>


{% endblock %}

groups/templates/groups/group_form.html
<!DOCTYPE html>
{% extends "groups/group_base.html" %}
{% load bootstrap5 %}

{% block body_blcok %}
    {% block group_content %}
        <h4>Create New Group !</h4>
        <form  method='POST' id="groupForm">
            {% csrf_token %}
            {% bootstrap_form form%}
            <input type="submit" class="btn btn-lg btn-primary" value="Create">
        </form>
    {% endblock %}
{% endblock %}

groups/templates/groups/group_list.html
{% extends "groups/group_base.html" %}

{% block pregroup %}
<div class="col-md-4">
    <div class="content">
        {% if user.is_authenticated %}
            <h2>
                Welcome Back <a href="{% url 'posts:for_user' username=user.username %}">
                    @{{user.username}}
                </a>
            </h2>
        {% endif %}

        <h2>Groups:</h2>
        <p>Welcom to Group</p>
    </div>
    {% if user.is_authenticated %}
        <a href="{% url 'groups:create' %}" class="btn btn-lg btn-fill btn-waring"><i class="bi bi-node-plus-fill"></i>Create New Group</a>
    {% endif %}
</div>
{% endblock %}

{% block group_content %}
    <div class="col-md-8">
        <div class="list-group">
            {% for group in object_list %}
                <a href="{% url 'groups:single' slug=group.slug %}" class="list-group-item "> 
                    <h3 class="title list-group-item-heading ">{{group.name}}</h3>
                    <div class="list-group-item-text contaniner-fluid">
                        {{group.description_html|safe}}

                        <div class="row">
                            <div class="col-md-4">
                                <span >{{ group.members.count }}</span>
                                member{{ group.members.count|pluralize }}

                            </div>
                            <div class="col-md-4">
                                <span class="">{{group.posts.count}}</span>
                                post{{group.posts.count|pluralize}}

                            </div>

                        </div>

                    </div>
                </a>

            {% endfor %}

        </div>

    </div>
{% endblock %}