accounts/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views
from simplesocial import settings


app_name = 'accounts'
urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name = 'accounts/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout', kwargs={'next_page':settings.LOGOUT_REDIRECT_URL}),
    path('signup/', views.SinUp.as_view(), name='signup'),
]

posts/urls.py
from django.urls import path
from . import views

app_name='posts'

urlpatterns = [
    path('', views.PostList.as_view(), name='all'),
    path('new/', views.CreatePost.as_view(), name='create'),
    path('by/<str:username>/', views.UserPosts.as_view(), name='for_user'),
    path('by/<str:username>/<int:pk>/', views.PostDetail.as_view(), name='single'),
    path('delete/<int:pk>/', views.DeletePost.as_view(), name='delete'),

    #personalpost model
    path('personalpost/', views.PorsonalPostList.as_view(), name='personalpost'),
    path('personalpost/new/', views.PersonalPostCreate.as_view(), name='createpost'),
    path('personalpost/detail/<int:pk>/', views.PersonalPostDetail.as_view(), name='post_detail'),
    path('personalpost/remove/<int:pk>/', views.PersonalPostDelete.as_view(), name='deletepost'),
]

simplesocial/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.HomePage.as_view(), name='home'),
    path('accounts/',include('accounts.urls', namespace='accounts')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('test/', views.TestPage.as_view(), name='test'),
    path('thanks/', views.ThanksPage.as_view(), name='thanks'),
    path('groups/',include('groups.urls', namespace='groups')),
    path('posts/', include('posts.urls', namespace='posts')),
    path('comments/', include('comments.urls', namespace='comments')),


]

templates/base.html
<!DOCTYPE html>
{% load bootstrap5 %}
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}  Document {% endblock%}</title> 
    {% bootstrap_css %}
    {% bootstrap_javascript %}

    <!-- ICON OF BOOTSTRAP -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.8.1/font/bootstrap-icons.css">
    <!-- ICON OF SITE ICON8 -->
    

    <!-- GOOGLE FONTS -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@700;900&family=Ubuntu&display=swap" rel="stylesheet">

    <!-- CSS  -->
    <!-- CSS LINK MESTER.CSS -->
    <link rel="stylesheet" href="{% static 'simplesocial/css/master.css' %}">
    <!-- CSS LINK MYEDIT.CSS  -->
    <link rel="stylesheet" href="{% static 'simplesocial/css/myedit.css' %}">

</head>
<body>
  <!-- OLD VERSION OF NAVBAR  -->
    <!-- <nav class="navbar navbar-expand-lg navbar-light bg-light techfont costom-navbar mynav" role="navigation", id="navbar">
        <div class="container">
            <a class="navbar-barand mynav" href="{% url 'home' %}">Start Social</a>

            <ul class="nav navbar-nav navbar-right">
                {% if user.is_authenticated %}
                    <li><a href="{% url 'posts:create' %}">Post</a></li>
                    <li><a href="{% url 'groups:all' %}">Groups</a></li>
                    <li><a href="{% url 'groups:create' %}">Create Group</a></li>
                    <li><a href="{% url 'accounts:logout' %}">Logout</a></li>
                {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'groups:all' %}">Groups</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'accounts:login' %}">Login</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'accounts:signup'%}">Signup</a>
                    </li>
                {% endif %}


            </ul>

        </div>

    </nav> -->

    <!-- NEW VERSION OF NAVBAR  -->
    <nav class="navbar navbar-expand-lg navbar-light bg-light ">
        <div class="container">
          <a class="navbar-brand" href="#">BluePath</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            {% if user.is_authenticated %}
            <ul class="navbar-nav">
              
              <li class="nav-item">
                  <!-- Home -->
                <a class="nav-link active" aria-current="page" href="{% url 'home' %}"><i class="bi bi-house"></i></a>
              </li>
              <li class="nav-item">
                  <!-- ADD POST -->
                <a class="nav-link" href="{% url 'posts:createpost' %}"><i class="bi bi-pencil-square"></i></a>
              </li>
              <li class="nav-item">
                  <!-- LIST  -->
                <a class="nav-link" href="{% url 'posts:personalpost' %}"><i class="bi bi-card-list"></i></a>
              </li>
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                    <!-- GROUPS  -->
                    <i class="bi bi-people-fill"> groups</i>
                  
                </a>
                <!-- DROPMENU  -->
                <ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                  <li><a class="dropdown-item" href="{% url 'posts:create' %}">Create Group</a></li>
                  <li><a class="dropdown-item" href="{% url 'groups:all' %}">Groups</a></li>
                  <li><a class="dropdown-item" href="{% url 'groups:create' %}">Add Post Group</a></li>
                </ul>
              </li>
            </ul>

            <!-- RIGHT NAVBAR -->
            <!-- DROPDOWN FRO RIGHT SIDE  -->
            <ul class='nav navbar-nav navbar-right ms-auto ' >
              <li class="nav-item">
                <!-- ADD POST -->
              <a class="nav-link" href="{% url 'accounts:logout' %}"><i class="bi bi-box-arrow-left"></i></a>
            </li>
            </ul>

            <!-- IF USER NOT LOGIN  -->
            {% else %}
            <ul class="navbar-nav">
              
              <li class="nav-item">
                  <!-- Home -->
                <a class="nav-link active" aria-current="page" href="{% url 'home' %}"><i class="bi bi-house"></i></a>
              </li>
              
              <li class="nav-item">
                  <!-- LIST  -->
                <a class="nav-link" href="{% url 'posts:personalpost' %}"><i class="bi bi-card-list"></i></a>
              </li>
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                    <!-- GROUPS  -->
                    <i class="bi bi-people-fill"> groups</i>
                  
                </a>
                <!-- DROPMENU  -->
                <ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                  <li><a class="dropdown-item" href="{% url 'posts:create' %}">Create Group</a></li>
                  <li><a class="dropdown-item" href="{% url 'groups:all' %}">Groups</a></li>
                  <li><a class="dropdown-item" href="{% url 'groups:create' %}">Add Post Group</a></li>
                </ul>
              </li>
            </ul>

            <!-- RIGHT NAVBAR -->
            <!-- DROPDOWN FRO RIGHT SIDE  -->
            <ul class='nav navbar-nav navbar-right ms-auto ' >
              <li class="nav-item dropdown">
                  <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                      <i class="bi bi-person-circle"></i>
                  </a>
                  <ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                      <li><a class="dropdown-item" href="{% url 'accounts:login' %}">Login</a></li>
                      <li><a class="dropdown-item" href="{% url 'accounts:signup' %}">Signup</a></li> 
                    </ul>
              </li>
          </ul>

            {% endif %}
          </div>
        </div>
      </nav>
    {% block body_blcok %}

    {% endblock %}
    <script src="{% static 'simplesocial/js/scripts.js'%}">

    </script>
</body>
</html>

templates/index.html
{% extends 'base.html' %}
<title>{% block title %}  Home {% endblock%}</title>

{% block body_blcok %}

<h1>Home page </h1>

{% endblock %}

templates/test.html
{% extends 'base.html' %}
<title>{% block title %}  Home {% endblock%}</title>

{% block body_blcok %}

<h1>See you later </h1>

{% endblock %}

templates/thanks.html
{% extends 'base.html' %}
<title>{% block title %}  Home {% endblock%}</title>

{% block body_blcok %}

<h1>Thanks for Login </h1>

{% endblock %}