comments/urls.py
from unicodedata import name
from django.urls import path
from . import views

app_name='comments'

urlpatterns =[
    path('personalpost/<int:pk>/comment/', views.add_comment_personalpost, name='addcomment'),
    path('comment/<int:pk>/delete/', views.comment_delete, name='remove')
]

posts/urls.py
from django.urls import path
from . import views

app_name='posts'

urlpatterns = [
    path('', views.PostList.as_view(), name='all'),
    path('new/', views.CreatePost.as_view(), name='create'),
    path('by/<str:username>/', views.UserPosts.as_view(), name='for_user'),
    path('by/<str:username>/<int:pk>/', views.PostDetail.as_view(), name='single'),
    path('delete/<int:pk>/', views.DeletePost.as_view(), name='delete'),

    #personalpost model
    path('personalpost/', views.PorsonalPostList.as_view(), name='personalpost'),
    path('personalpost/new/', views.PersonalPostCreate.as_view(), name='createpost'),
    path('personalpost/detail/<int:pk>/', views.PersonalPostDetail.as_view(), name='post_detail'),
    path('personalpost/remove/<int:pk>/', views.PersonalPostDelete.as_view(), name='deletepost'),
]

simplesocial/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.HomePage.as_view(), name='home'),
    path('accounts/',include('accounts.urls', namespace='accounts')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('test/', views.TestPage.as_view(), name='test'),
    path('thanks/', views.ThanksPage.as_view(), name='thanks'),
    path('groups/',include('groups.urls', namespace='groups')),
    path('posts/', include('posts.urls', namespace='posts')),
    path('comments/', include('comments.urls', namespace='comments')),


]

posts/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth import get_user_model
from groups.models import Group
import misaka
from django.conf import settings
from django.contrib.auth import get_user_model
from django.utils import timezone
User = get_user_model()

# Create your models here.

class Post(models.Model):
    user = models.ForeignKey(User, related_name='posts', on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now=True)
    message = models.TextField()
    message_html = models.TextField(editable=False)
    group = models.ForeignKey(Group, related_name='posts', on_delete=models.CASCADE, null=True, blank=True )

    def save(self, *args, **kwargs):
        print('###############################################################################hi moood ')
        self.message_html = misaka.html(self.message)
        print('&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&')
        super().save(*args, **kwargs)

       


    def __str__(self):
        return self.message

    
    def get_absolute_url(self):
        return reverse('posts:single', kwargs={'username':self.user.username,'pk':self.pk})


    class Meta():
        ordering = ['-created_at']
        unique_together = ['user', 'message']

class PersonalPost(models.Model):
    author = models.ForeignKey(User, related_name='personalposts', on_delete=models.CASCADE)
    title = models.CharField(max_length=200)
    text = models.TextField()
    create_date = models.DateTimeField(default=timezone.now)

    def get_absolute_url(self):
        return reverse('posts:post_detail', kwargs={'pk':self.pk})
        

    def __str__(self):
        return self.title

    class Meta():
        ordering = ['-create_date']
        # unique_together = ['author', 'title']

posts/views.py
from django.contrib import messages
from django.shortcuts import render
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from django.views import generic
from comments.models import Comment
from braces.views import SelectRelatedMixin
from django.http import Http404
from . import models
from django.utils import timezone

from django.contrib.auth import get_user_model
User = get_user_model()
# Create your views here.

#what is SelectRelatedMixin:A simple mixin which allows you to specify a list or
# tuple of foreign key fields to perform a select_related on
class PostList(SelectRelatedMixin, generic.ListView):
    model = models.Post
    select_related = ('user', 'group')

class UserPosts(generic.ListView):
    model = models.Post
    template_name = 'posts/user_post_list.html'

    def get_queryset(self):
        try:
            self.post_user = User.objects.prefetch_related('posts').get(username__iexact=self.kwargs.get('username'))

        except User.DoesNotExist:
            raise Http404

        else:
            return self.post_user.posts.all()

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        context['post_user']= self.post_user
        return context


class PostDetail(SelectRelatedMixin, generic.DetailView):
    model = models.Post
    select_related  = ('user', 'group')

    def get_queryset(self):
        queryset = super().get_queryset()
        return queryset.filter(user__username__iexact=self.kwargs.get('username'))

class CreatePost(LoginRequiredMixin, SelectRelatedMixin, generic.CreateView):
    model = models.Post
    fields = ['message', 'group']

    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.user = self.request.user
        self.object.save()
        return super().form_valid(form)

    # def form_valid(self, form):
    #     self.object = form.save(commit=False)
    #     self.object.user = self.request.user
    #     self.object.save()
    #     return super().form_valid(form)
        # form.instance.created_by = self.request.user
        # return super().form_valid(form)

class DeletePost(LoginRequiredMixin, SelectRelatedMixin, generic.DeleteView):
    model = models.Post
    select_related = ('user', 'group')
    success_url = reverse_lazy('posts:all')

    def get_queryset(self):
        queryset = super().get_queryset()
        print(f"is from post gorup delete {queryset.filter(user_id=self.request.user.id)} &&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&")
        return queryset.filter(user_id=self.request.user.id)

    def delete(self, *args, **kwargs):
        messages.success(self.request,'Post Delete')
        print(f"$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$ is messages delete {messages.success(self.request,'Post Delete')}")
        print(f"^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ is the result of delet function {super().delete(*args, **kwargs)}")
        return super().delete(*args, **kwargs)



'''Personal Posts Here'''
class PorsonalPostList(generic.ListView):
    model = models.PersonalPost

    def get_queryset(self):
        return models.PersonalPost.objects.filter(create_date__lte= timezone.now()).order_by('-create_date')

class PersonalPostCreate(LoginRequiredMixin, generic.CreateView):
    model = models.PersonalPost
    fields = ['title', 'text']

    #Here I have fields call 'author' but I don't want user enter this field. here by this funtion ↓
    # I let 'author' get 'username' by defualt 

    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.author = self.request.user
        self.object.save()
        return super().form_valid(form)

class PersonalPostDetail(generic.DetailView):
    model=models.PersonalPost

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        context['personalpost_list']= models.PersonalPost.objects.all()
        # context['comment_list'] = Comment.objects.all()
        # context['comment_list'] = Comment.comments_set.order_by('-create_date')

        
        return context
    

class PersonalPostDelete(LoginRequiredMixin, SelectRelatedMixin, generic.DeleteView):
    model = models.PersonalPost
    success_url = reverse_lazy('posts:personalpost')
    select_related = ("author",)

    # def get_queryset(self):
    #     queryset = super().get_queryset()
    #     print(f"this is queryset ************************{queryset}")

    #     print(f"this is queryset filter ************************{queryset.filter(author_id=self.request.user.id)}")
    #     return queryset.filter(author_id=self.request.user.id)

    # def delete(self, *args, **kwargs):
    #     messages.success(self.request,'Post Delete')
    #     return super().delete(*args, **kwargs)

posts/templates/posts/_post.html
<div class="post media">
    <h3>{{post.message_html|safe}}</h3>
    <div class="media-body">
        <strong>{{post.user.username}}</strong>
        <h5 class="media-heading">
            <span class="username">
                <a href="{% url 'posts:for_user' username=post.user.username %}">@{{post.user.username}}</a>

            </span>
            <time class="time">
                <a href="{% url 'posts:single' username=post.user.username pk=post.pk %}">{{post.created_at}}</a>

            </time>

        </h5>
        <div class="media-footer">
            {% if user.is_authenticated and post.user == user %}
            <a href="{% url 'posts:delete' pk=post.pk %}" title="delete" class="btn btn-simple">
                <i class="bi bi-x-octagon"></i>
                <span class="text-danger icon-label">Delete</span>
            </a>
            
            {% endif %}

        </div>

    </div>

</div>

posts/templates/posts/personalpost_confirm_delete.html
{% extends 'posts/post_base.html' %}
{% load bootstrap5 %}
<title>{% block title %}  Document {% endblock%}</title> 

{% block body_blcok %}
    <form class="form-label" method="POST">
        {% csrf_token %}
        <input type="submit" class="btn btn-danger" value="Delete Post">

    </form>
    <a href="{% url 'posts:post_detail' pk=personalpost.pk %}">Cancel</a>
{% endblock %}

posts/templates/posts/personalpost_detail.html
{% extends 'posts/post_base.html' %}
{% load bootstrap5 %}
{%load static %}
<title>{% block title %}  Document {% endblock%}</title> 

{% block body_blcok %}
<!-- <h1>I'm from Personal post details</h1>
<div class="centerstage">
    
    <div class="contaner-fluid post">
        <h1><a href="{% url 'posts:post_detail' pk=personalpost.pk %}">{{personalpost.title}}</a></h1>

        <h2>{{personalpost.text}}</h2>

        <div class="date">
            <p>Date: <a href="">{{personalpost.create_date|date:'d M Y'}}</a></p>
        </div>

        <div class="comment">
            <p>Comments: <a href="#">{{personalpost.title}}</a></p>
            
        </div>
        <a href="{%url 'posts:deletepost' pk=personalpost.pk %}">Delete</a>
    </div>
    
</div> -->

<!-- PersonalPost section  -->

<div class="container container-listdetail">
    <img class="user-image" src="{% static 'simplesocial/image/20200102_022607.jpg'%}" alt="">
    <a class="a-listdetail" href="">@{{personalpost.author}} is user id{{user.id}}</a>
    <p class="p-listdetail">{{personalpost.create_date|date:'d M Y'}} {{personalpost.author.id}}</p>
    
    <h1 class="topic-header"><a href="{% url 'posts:post_detail' pk=personalpost.pk %}">{{personalpost.title}}</a></h1>

    <p>{{personalpost.text}}</p>
    
    <!-- For Delete Personalpost AND add comment  -->
    {% if user.is_authenticated and user.id == personalpost.author.id %}
    <a href="{%url 'posts:deletepost' pk=personalpost.pk %}">Delete</a>
    <h1>{{personalpost.pk}}</h1>
    <a href="{% url 'comments:addcomment' pk=personalpost.pk %}">Add comment</a>
    <hr>
    {% else %}
        <a href="{%url 'posts:personalpost' %}"> <span> ↩Back </span></a>

        <a href="{% url 'comments:addcomment' pk=personalpost.pk %}">Add comment</a>
        <hr>
    {% endif %}
    <!-- Comment section. show all comments -->
    <h3>comment</h3>
    {% for comment1 in personalpost.comments.all %}
        <img class="user-image" src="{% static 'simplesocial/image/20200102_022607.jpg'%}" alt="">
        <a class="a-listdetail" href="">@{{comment1.comment_author}} is user id{{user.id}}</a>
        <p class="p-listdetail">{{comment1.create_date|date:'d M Y'}} </p>
        <br>
        
        <p>{{comment1.comment}}</p>
        <!-- For Delete Comment  -->
        {% if user.is_authenticated %}
            {% if user.id == personalpost.author.id or user.id == comment1.comment_author.id %}
        <a href="{% url 'comments:remove' pk=comment1.pk%}">Delete</a>
            {% endif %}
        {% endif %}
        <hr>
    {% endfor %}
</div>


<!-- Show All list of topics  -->
<div class="container container-relatedlist">
    <h3>list  of topic:</h3>
    <hr>
    {% for post in personalpost_list %}
    
    <p><a href="{% url 'posts:post_detail' pk=post.pk %}">{{post.title}}</a></p>
    {% endfor %}

</div>
{% endblock %}

posts/templates/posts/personalpost_form.html
<!DOCTYPE html>
{% extends 'posts/post_base.html' %}
{% load bootstrap5 %}
<title>{% block title %}  Document {% endblock%}</title> 

{% block body_blcok %}
<form action="" method="POST">
    {% csrf_token %}
    {% bootstrap_form form %}
    <input type="submit" class="btn btn-lg btn-primary" value="Add personal Post">

</form>

{% endblock %}

posts/templates/posts/personalpost_list.html
<!DOCTYPE html>
{% extends 'posts/post_base.html' %}
{% load bootstrap5 %}
<title>{% block title %}  Document {% endblock%}</title> 

{% block body_blcok %}
<h1>I'm from Personal post list</h1>
<div class="centerstage">
    <!-- {% for post in personalpost_list %}
    <div class="contaner-fluid post">
        <h1><a href="{% url 'posts:post_detail' pk=post.pk %}">{{post.title}}</a></h1>

        <div class="date">
            <p>Date: <a href="">{{post.create_date|date:'d M Y'}}</a></p>
        </div>

        <div class="comment">
            <p>Comments: <a href="#">{{post.title}}</a></p>
            
        </div>
        {% endfor %}
    </div> -->

    <div class="container px-4 px-lg-5">
        <div class="row gx-4 gx-lg-5 justify-content-center">
            <div class="col-md-10 col-lg-8 col-xl-7">
                {% for post in personalpost_list %}
                <!-- Post preview-->
                <div class="post-preview">

                    <a href="{% url 'posts:post_detail' pk=post.pk %}">

                        <h2 class="post-title">{{post.title}}</h2>
                        <h3 class="post-subtitle">{{post.title}}</h3>
                    </a>
                    <p class="post-meta">
                        Posted by
                        <a href="#!">{{post.author}}</a>
                        on {{post.create_date|date:'d M Y'}}
                    </p>
                </div>

                <!-- Divider-->
                <hr class="my-4" />

            {% endfor %}

                <div class="d-flex justify-content-end mb-4"><a class="btn btn-primary text-uppercase" href="#!">Older Posts →</a></div>
            </div>
        </div>
    </div>

{% endblock %}

posts/templates/posts/post_base.html
{% extends 'base.html' %}

{% block content %}

<div class="posts-page">
    <div class="container">
        <div class="row">
            {% block prepost %}{% endblock %}
            {% block post_content %}{% endblock %}
            {% block post_post %}{% endblock %}
        </div>
    </div>
</div>

{% endblock %}

posts/templates/posts/post_confirm_delete.html
<!DOCTYPE html>
{% extends 'posts/post_base.html' %}
{% load bootstrap5 %}
<title>{% block title %}  Document {% endblock %}</title> 

{% block body_blcok %}
    {% block post_content %}
        <h3>Are you sure you want to delete this post?</h3>
        <div class="posts">
            {% include "posts/_post.html" with post=object hide_delete=True %}
        </div>
        <form method="POST">
            {% csrf_token %}
            <input type="submit" value="Confirm Delete" class="btn btn-danger btn-large">
            <!-- <a href="{% url 'posts:single' username=user.username pk=object.pk %}" class="btn btn-simple btn-lg btn-default">
                Cancel
            </a> -->

        </form>
        <a href="{% url 'posts:single' username=user.username pk=object.pk %}" class="btn btn-simple btn-lg btn-default">
            Cancel
        </a>
    {% endblock %}
{% endblock %}

posts/templates/posts/post_detail.html
<!DOCTYPE html>
{% extends 'posts/post_base.html' %}
{% load bootstrap5 %}
<title>{% block title %}  Document {% endblock%}</title> 

{% block body_blcok %}
    {% block post_content %}
        <div  class="col-md-8">
            {% include "posts/_post.html" %}
        </div>
    {% endblock %}
{% endblock %}

posts/templates/posts/post_form.html
<!DOCTYPE html>
{% extends 'posts/post_base.html' %}
{% load bootstrap5 %}
<title>{% block title %}  Document {% endblock%}</title> 

{% block body_blcok %}
    {% block prepost %}

    <h4>Create anew Post</h4>
    <form action="{% url 'posts:create'%}" method="POST" id="postForm">
        {% csrf_token %}
        {% bootstrap_form form %}
        <input type="submit" class="btn btn-lg btn-primary" value="Add Post">
    </form>

    {% endblock %}
{% endblock %}

posts/templates/posts/post_list.html
<!DOCTYPE html>
{% extends 'posts/post_base.html' %}
{% load bootstrap5 %}
<title>{% block title %}  Document {% endblock%}</title> 

{% block body_blcok %}

    <!-- PREPOST -->
    {% block prepost %}
        <div class="col-md-4">
            {% if request.user.is_authenticated %}
                <div class="card card-with-shadow">
                    <div class="content">
                        <h5 class="title"> Your Group</h5>
                        <ul class="list-unstyled">
                            {% for  member_group in get_user_group %}
                            <li class="group li-with-bullet">
                                <a href="{% url 'group:single' slug=member_group.group.slug %}">{{member_group}}</a>
                            </li>
                            {% endfor %}
                        </ul>
                    </div>
                </div>
            {% endif %}
            <div class="card card-with-shadow">
                <div class="content">
                    <h5 class="title">All Groups</h5>
                    <ul class="list-unstyled">
                        {% for other_groups in get_other_groups %}
                            <li class="group li-with-bullet">
                                <a href="{% url 'groups:single' slug=other_group.slug %}"></a>
                            </li>
                        {% endfor %}

                    </ul>

                </div>

            </div>
        </div>
    {% endblock %}


    {% block post_content %}
        <div class="col-md-8">
            {% for post in post_list %}
                {% include 'posts/_post.html' %}
            {% endfor %}

        </div>
    {% endblock %}

{% endblock %}

posts/templates/posts/user_post_list.html
<!DOCTYPE html>
{% extends 'posts/post_base.html' %}
{% load bootstrap5 %}
<title>{% block title %}  Document {% endblock%}</title> 

{% block body_blcok %}
    {% block prepost %}
        <div  class="col-md-4">
            <h1>@{{post_user.username}}</h1>
        </div>
    {% endblock %}
    {% block post_content %}
        <div  class="col-md-8">
            {% for post in post_list %}
                {% include "posts/_post.html" %}
            {% endfor %}
        </div>
    {% endblock %}
{% endblock %}